# While

In [ ]:
# Ciclo while infinito
while True:
  print("Hola Mundo!!!")

Se han truncado las últimas 5000 líneas del flujo de salida.
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
H

KeyboardInterrupt: ignored

In [ ]:
# Ciclo while infinito
n=0

while True:
  print("Hola Mundo!!!")
  n+=1
  if n==10:
    break

Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!
Hola Mundo!!!


In [ ]:
condicion=True

# Los simbolos != en conjunto significan diferente de:
while condicion!=False:
  print("Hola mundo!!!")
  condicion=False


Hola mundo!!!


In [ ]:
condicion=True

for n in range(10):
  #condicion+=1
  while condicion!=False:
    print("Hola mundo!!!")
    condicion=0

Hola mundo!!!


In [ ]:
print(True==1)

True


In [ ]:
print(False==0)

True


In [ ]:
edad=int(input("Dame tu edad: "))

Dame tu edad: Edgar


ValueError: ignored

In [ ]:
while True:
  try:
    edad=int(input("Dame tu edad: "))
    break
  except:
    print("Error")

Dame tu edad: hola
Error
Dame tu edad: 33.5
Error
Dame tu edad: 789.5
Error
Dame tu edad: Hola
Error
Dame tu edad: Mundo
Error
Dame tu edad: 55


In [ ]:
# Ejemplo implementandolo a un cajero automático

nip=2020

while True:
  # Verificando que pin sea numérico
  try:
    pin=int(input("Dame tu pin: "))
    # Verificando que pin sea igual a nip
    if pin!=nip:
      print("Error de pin")
    else:
      print("Acceso concedido!!!")
      break
  except:
    print("Error de valor")

Dame tu pin: 3.15
Error de valor
Dame tu pin: lola
Error de valor
Dame tu pin: 9874
Error de pin
Dame tu pin: 2020
Acceso concedido!!!


# Try - Except

In [ ]:
print("Esto es un texto, pero la linea de abajo es una variable")
try:
  print (Edgar[0])
except NameError:
  print("No se pudo imprimir la variable Edgar")
except:
  print("Estás cometiendo un error de ortografía en la segunda línea de tu programa")
print("Hola Mundo!!!")

Esto es un texto, pero la linea de abajo es una variable
No se pudo imprimir la variable Edgar
Hola Mundo!!!


# Definición de funciones

In [ ]:
def cosulta_pin():
  nip=2020

  while True:
    # Verificando que pin sea numérico
    try:
      pin=int(input("Dame tu pin: "))
      # Verificando que pin sea igual a nip
      if pin!=nip:
        print("Error de pin")
      else:
        print("Acceso concedido!!!")
        break
    except:
      print("Error de valor")

In [ ]:
cosulta_pin()

Dame tu pin: 2020
Acceso concedido!!!


In [ ]:
cosulta_pin()

Dame tu pin: Edgar
Error de valor
Dame tu pin: 5656
Error de pin
Dame tu pin: 2020
Acceso concedido!!!


In [ ]:
def edad_nombre():
  # Solicitando la edad:
  while True:
    try:
      edad=int(input("Dame tu edad: "))
      break
    except:
      print("Error, el valor ingresado no corresponde a una edad")
  
  # Solicitando el nombre:
  while True:
    try:
      nombre=input("Dame tu Nombre: ")
      if nombre.isalpha()==True:
        break
      else:
        print("Error en el nombre ingresado")  
    except:
      print("Error en el nombre ingresado")
  
  print("Tu nombre es:", nombre)
  print("Tu edad es:", edad)

In [ ]:
edad_nombre()

Dame tu edad: 33
Dame tu Nombre: Edgar
Tu nombre es: Edgar
Tu edad es: 33


In [ ]:
# Un signo de igual equivale a asignación:
edad=30

# Dos signos de igual equivale a comparación
edad==55

False

In [ ]:
# Dentro de los parentesis van los argumentos de la función
# Están las funciones que devuelven un objeto:
def area_circulo1(radio):
  print("El área del círculo es igual a:")
  return 3.1416*radio*radio


In [ ]:
circulo_10=area_circulo1(10)

El área del círculo es igual a:


In [ ]:
type(circulo_10) ,circulo_10

(float, 314.16)

In [ ]:
# Están las funciones que no devuelven valor:
def area_circulo2(radio):
  print(3.1416*radio*radio)

In [ ]:
area_circulo2(10)

314.16


In [ ]:
circulo_10=area_circulo2(10)

314.16


In [ ]:
type(circulo_10) ,circulo_10

(NoneType, None)

In [ ]:
circulo_10

In [ ]:
def pos_neg(numero):
  if numero>0:
    return "Postivo"
  elif numero<0:
    return "Negativo"
  else:
    return "Cero"

In [ ]:
pos_neg(0)

'Cero'

In [ ]:
def mensaje_bienvenida():
  print(" ","-"*29)
  print("|"," "*28,"|")
  print("|"," "*8,"Bienvenidos"," "*7,"|")
  print("|"," "*28,"|")
  print(" ", "-"*29)

In [ ]:
mensaje_bienvenida()

  -----------------------------
|                              |
|          Bienvenidos         |
|                              |
  -----------------------------


In [ ]:
mensaje=mensaje_bienvenida()

  -----------------------------
|                              |
|          Bienvenidos         |
|                              |
  -----------------------------


In [ ]:
mensaje

# Librerias

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
!pip install gTTS

In [ ]:
from gtts import gTTS

In [ ]:
mytext = 'Hello World!!!'

language = 'en'

myobj = gTTS(text=mytext, lang=language, slow=False) 

myobj.save("welcome.mp3")

In [ ]:
def mensaje_computadora(texto, idioma):
  from gtts import gTTS
  myobj = gTTS(text=texto, lang=idioma, slow=False) 
  myobj.save(texto+".mp3")

In [ ]:
# Importando el diccionario de idiomas
from gtts import lang

In [ ]:
lang.tts_langs()["es"]

'Spanish'

In [ ]:
mensaje_computadora("Hola a todos, gracias por venir","es")

In [ ]:
# Librería de algebra lineal
import numpy as np

In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

In [ ]:
np.random.rand()

0.7196514522115145

In [ ]:
np.random.randint(-10,10)

-10

In [ ]:
np.random.rand(100)

array([0.31518238, 0.93051617, 0.01046365, 0.95152876, 0.98916717,
       0.73104547, 0.77184746, 0.87117885, 0.76183442, 0.95400143,
       0.45937734, 0.55682698, 0.57182769, 0.28720267, 0.16216244,
       0.64914138, 0.18745568, 0.70585466, 0.79421621, 0.25026923,
       0.55240059, 0.49033573, 0.66252813, 0.14576162, 0.76370044,
       0.24148491, 0.11566525, 0.65746554, 0.96056346, 0.08289013,
       0.35165237, 0.68676299, 0.43077291, 0.36493761, 0.70534854,
       0.48089794, 0.89313335, 0.00521867, 0.98692696, 0.05458917,
       0.60926535, 0.27909899, 0.48602566, 0.35446667, 0.32473826,
       0.66265282, 0.47894093, 0.63103003, 0.78627603, 0.86028487,
       0.04432719, 0.37109055, 0.36904636, 0.29997148, 0.26919934,
       0.38844794, 0.03221601, 0.15119061, 0.25398359, 0.67830143,
       0.35454816, 0.98439969, 0.78632419, 0.77516269, 0.06209355,
       0.85629761, 0.53354873, 0.96104563, 0.73828477, 0.74159811,
       0.72277669, 0.01006229, 0.74626875, 0.06339787, 0.19249

In [ ]:
np.random.randint(-10,10,100)

array([ -4,  -3,  -2,  -5,   9,  -1, -10,   6,  -8,  -7,   7,  -1,  -4,
         8,   9,   5,   2,  -7,  -7, -10,  -1,  -9,  -1,  -9,   7,   5,
        -6, -10,  -3,   8,   6,  -2,  -4, -10,   4,   8,   7,  -1,  -5,
         8,   3,   9,   2,  -1,  -1,  -5,  -5,   7,  -8, -10,  -5,   9,
        -2,   5,   4,  -5,   7,   0,   3,   3,   9,  -7,  -6,  -4,  -2,
         3,  -3,  -9,   8,  -3,  -1,   9,   1,  -5,  -9, -10,   2,  -8,
         6,   0,   2,   4,  -4,   5,   6,   4,   0,  -7,  -6,  -4,   5,
         4,   8,  -3,   6,   4,  -9,   1,   9, -10])

In [ ]:
np.random.normal(size=200)

array([-0.00571902, -0.0582672 , -0.20756946,  0.2762468 , -1.08298163,
       -0.48959592,  1.82387356,  0.68576379,  0.69870894, -0.12082513,
       -1.791248  , -1.84603754, -2.67154856,  0.10982738, -0.82189226,
       -1.2052439 , -0.10688685,  0.85051142,  0.16896074, -1.6437539 ,
        1.45715755,  0.46908385, -0.22126963,  0.65913841,  0.88255359,
        0.48971682, -0.46866538, -1.11316732, -2.274319  , -0.04661523,
        0.17533481, -0.02320315,  0.50429876,  0.1366126 , -1.21718452,
        0.00605371,  0.87409582,  1.52885465,  1.51355797,  0.20965816,
        0.96460241,  0.08163398,  0.77740845, -0.58969129,  0.41858223,
        1.7109089 , -1.06088974, -0.20141038,  0.25636125, -1.16533451,
        0.88498313,  0.48480734,  0.55900536, -0.3506714 ,  0.10120817,
       -1.45962107,  1.7928759 ,  1.33728291, -0.51133236,  3.25414066,
       -0.71978672,  0.66833425,  0.05858361, -0.0168988 , -0.96463603,
        1.89025791,  1.23295744, -0.95133757,  0.48947514,  1.09

In [ ]:
import random

In [ ]:
random.random()

0.28637508700846726

In [ ]:
?np.random.pareto

In [ ]:
normal=np.random.normal(size=100)

In [ ]:
type(normal)

numpy.ndarray

In [ ]:
lista=[2,3,5,7,8,6,9,4,5,1,3,9,7]

In [ ]:
sum(lista)/len(lista)

5.3076923076923075

In [ ]:
np.array(lista).mean()

5.3076923076923075

# Proyecto 1

**Juego Adivinar el número**

In [ ]:
def juego_aleatorio():
  import numpy as np

  aleatorio=np.random.randint(1,100)
  intentos=0

  while True:
    try:
      numero=int(input("Dame un número entero: "))
      intentos+=1
      if numero==aleatorio:
        print("\n\n\n","-"*40)
        print("Felicidades, has adivinado el número")
        print("El número de intentos fué", intentos)
        break
      elif numero>aleatorio:
        print("El número ingresado es mayor")
      else:
        print("El número ingresado es menor")
    except:
      intentos+=1
      print("El valor ingresado no es un número entero")

In [ ]:
juego_aleatorio()

El valor ingresado no es un número entero
El valor ingresado no es un número entero
El valor ingresado no es un número entero
